Add release note for EndpointSlice changes
submariner-io/submariner-website pull request #1002
Opened 2023-07-29 15:30 UTC by tpantelis

2023-08-01 13:23 UTC, vthapar requested changes

2023-08-01 13:23 UTC, vthapar commented on src/content/community/releases/_index.en.md
> +  Endpoints for all conditions are included - prior relases only published ready endpoints.
```suggestion
  Endpoints for all conditions are included now, prior releases only published ready endpoints.
```

2023-08-01 17:59 UTC, sridhargaddam approved these changes

2023-08-02 13:20 UTC, dfarrell07 approved these changes

2023-08-08 05:27 UTC, vthapar approved these changes

2023-08-08 05:35 UTC, merged