Add release notes for subctl PR#868
submariner-io/submariner-website pull request #1025
Opened 2023-09-15 14:12 UTC by tpantelis

Release notes for https://github.com/submariner-io/subctl/pull/868

2023-09-15 14:49 UTC, skitt requested changes

2023-09-15 14:49 UTC, skitt commented on src/content/community/releases/_index.en.md
> +* `subctl verify` no longer requires the KUBCONFIG environment variable to be set.
```suggestion
* `subctl verify` no longer requires the KUBECONFIG environment variable to be set.
```

2023-09-16 12:29 UTC, sridhargaddam approved these changes

2023-09-18 13:18 UTC, skitt approved these changes

2023-09-18 13:18 UTC, merged