Link to archives of missing RHACM+SubM blogs
submariner-io/submariner-website pull request #1031
Opened 2023-09-19 19:54 UTC by dfarrell07

The broken link tests recently started failing on these two posts.

They also 404 for me. Other posts from the same blogger still work.

Fixes: #1026

2023-09-19 23:00 UTC, tpantelis approved these changes

2023-09-20 05:46 UTC, sridhargaddam commented on src/content/other-resources/_index.en.md
> +* [Deep Dive with RHACM and Submariner - Connecting multicluster overlay networks (2021-04)](https://web.archive.org/web/20230531045006/https://rcarrata.com/openshift/rhacm-submariner/)
This seems to have moved here.
https://rcarrata.com/openshift/multicluster/networking/kubernetes/rhacm-submariner/

2023-09-20 05:46 UTC, sridhargaddam commented on src/content/other-resources/_index.en.md
> +* [Connecting stateful applications in multicluster environments with RHACM and Submariner (2021-04)](https://web.archive.org/web/20221130050657/https://rcarrata.com/openshift/rhacm-submariner-2/)
https://rcarrata.com/openshift/multicluster/networking/kubernetes/rhacm-submariner-2/

2023-09-21 07:10 UTC, skitt requested changes
See @sridhargaddam’s comments.

2023-10-23 21:07 UTC, closed without merging

2023-10-23 21:07 UTC, dfarrell07 commented
It seems the website's reorg has been reverted. The old links work again, the ones @sridhargaddam suggested no longer work.