Document commands for merging release notes
submariner-io/submariner-website pull request #1057
Opened 2023-10-18 15:43 UTC by dfarrell07

2023-10-18 19:09 UTC, dfarrell07 commented
Seems we need to do this with a rebase, not a merge, due to GitHub config that requires a rebase.

2023-10-20 08:06 UTC, skitt requested changes

2023-10-20 08:06 UTC, skitt commented on src/content/development/release-process/_index.en.md
> +they should be added to the release notes branch first and then rebased onto devel with an additional PR.
The old docs explain how to add commits to a pending merge branch — as I understand it, the above explains how to add changes once the first “merge” branch has been merged. Both scenarios are worth explaining.

2023-10-24 15:47 UTC, skitt approved these changes

2023-10-25 06:48 UTC, sridhargaddam approved these changes

2023-10-25 06:49 UTC, merged