Add release notes for 0.14.7
submariner-io/submariner-website pull request #1066
Opened 2023-10-31 23:18 UTC by aswinsuryan

2023-11-02 07:19 UTC, sridhargaddam requested changes
These notes should first be added to the release branch and sync'ed from there.

2023-11-02 17:46 UTC, tpantelis requested changes

2023-11-02 17:46 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +
Also need https://github.com/submariner-io/submariner/pull/2531:

"_The Submariner gateway now retries reading local node information on startup to reduce pod restarts if the Kubernetes API server is temporarily unavailable._"

and https://github.com/submariner-io/submariner/pull/2597:

"_Reduced data path downtime with Libreswan cable driver when gateway pod restarts._"

2023-11-03 02:15 UTC, tpantelis commented
> These notes should first be added to the release branch and sync'ed from there.

Instructions are [here](https://submariner.io/development/release-process/#release-notes-final-releases)

2023-11-03 13:00 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +
The first one above was not release-noted in other branches so I assume was deemed as not needing it.
The others are already included in the release-0.14 branch. We just need the ones a noted above in the  release-0.14 branch: https://github.com/submariner-io/submariner-website/pull/1073

2023-11-03 13:01 UTC, closed without merging