Add release notes for lighthouse PR #1430
submariner-io/submariner-website pull request #1068
Opened 2023-11-02 13:20 UTC by tpantelis

Release notes for https://github.com/submariner-io/lighthouse/pull/1430

2023-11-02 15:04 UTC, sridhargaddam requested changes

2023-11-02 15:04 UTC, sridhargaddam commented on src/content/community/releases/_index.en.md
> +* Fixed an issue in Service Discovery which could result in stale endpoint IPs returned from DNS queries.
```suggestion
* Fixed an issue in Service Discovery where stale endpoint IPs, corresponding to services that no longer exist, were returned from DNS queries.
```

2023-11-02 18:35 UTC, sridhargaddam approved these changes

2023-11-02 19:42 UTC, tpantelis commented
The link check job reports:

```
 ERROR: 1 dead links found!
  [✖] https://www.wireguard.com/ → Status: 0
```

However the link works for me.

2023-11-03 10:52 UTC, skitt approved these changes

2023-11-03 10:52 UTC, merged