Add release notes for subctl PR #978
submariner-io/submariner-website pull request #1075
Opened 2023-11-03 14:53 UTC by tpantelis

Release notes for https://github.com/submariner-io/subctl/pull/978

2023-11-03 14:59 UTC, sridhargaddam approved these changes

2023-11-06 13:46 UTC, skitt requested changes

2023-11-06 13:46 UTC, skitt commented on src/content/community/releases/_index.en.md
> +  sanity check when time is a constraint.
```suggestion
* The new `--only basic-connectivity` option on `subctl verify` runs a smaller set of connectivity tests as a quick
  sanity check when time is a constraint.
```

2023-11-14 00:54 UTC, dfarrell07 approved these changes

2023-11-16 08:18 UTC, skitt approved these changes

2023-11-16 08:18 UTC, merged