Add release note for submariner-io/submariner#2870
submariner-io/submariner-website pull request #1098
Opened 2024-01-09 18:49 UTC by aswinsuryan

2024-01-09 19:29 UTC, tpantelis requested changes

2024-01-09 19:29 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +  nongatewayroute CRs followed by a restart of route-agent pod.
```suggestion
* Fixed an issue with the OVN-Kubernetes CNI where, after a cluster recovery, the data path was broken requiring manual deletion of stale GatewayRoute and NonGatewayRoute resources and a restart of the Route Agent pod.
```

2024-01-09 20:11 UTC, aswinsuryan commented on src/content/community/releases/_index.en.md
> +  nongatewayroute CRs followed by a restart of route-agent pod.
done.

2024-01-09 20:12 UTC, tpantelis approved these changes

2024-01-10 07:54 UTC, maayanf24 approved these changes

2024-01-10 12:01 UTC, merged