0.16: release notes for submariner PR#3021
submariner-io/submariner-website pull request #1137
Opened 2024-05-30 15:02 UTC by aswinsuryan

Release notes for submariner-io/submariner#3021

2024-05-30 15:54 UTC, tpantelis requested changes

2024-05-30 15:54 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +## v0.16.5
```suggestion
## v0.16.6
```

2024-05-30 15:54 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +* Fixed an issue in Health Checker where a restart of health checker during event like a leader reelection would lead to invalid Pinger
```suggestion
* Health check counters on the Gateway resource now report correct information after a gateway leader re-election occurs.
```

2024-05-31 17:59 UTC, aswinsuryan commented on src/content/community/releases/_index.en.md
> +## v0.16.5
Done.

2024-05-31 17:59 UTC, aswinsuryan commented on src/content/community/releases/_index.en.md
> +* Fixed an issue in Health Checker where a restart of health checker during event like a leader reelection would lead to invalid Pinger
Done

2024-06-02 09:31 UTC, tpantelis approved these changes

2024-06-03 11:19 UTC, merged