Correct grammar and clarify deployment sentence in documentation.
submariner-io/submariner-website pull request #1142
Opened 2024-06-17 17:11 UTC by aswinayyolath

Correct grammar and clarify deployment sentence in documentation.

2024-06-18 07:27 UTC, vthapar requested changes
Avoid using 1st or 2nd person pronouns in documentation.

2024-06-18 07:27 UTC, vthapar commented on src/content/getting-started/architecture/broker/_index.en.md
> +While there are no services associated with the Broker, if you use ```subctl``` to deploy the Broker, an
```suggestion
While there are no services associated with the Broker, using ```subctl``` to deploy the Broker
```

2024-06-18 07:27 UTC, vthapar commented on src/content/getting-started/architecture/broker/_index.en.md
>  operator Pod is also deployed that installs the CRDs and the Globalnet configuration.
```suggestion
also deploys an operator Pod that installs the CRDs and the Globalnet configuration.
```

2024-06-18 12:18 UTC, skitt requested changes

2024-06-18 12:18 UTC, skitt commented on src/content/getting-started/architecture/broker/_index.en.md
> +also deploys an operator Pod that installs the CRDs and the Globalnet configuration.
```suggestion
While there are no Services associated with the Broker, using ```subctl``` to deploy the Broker
also deploys an operator Pod that installs the CRDs and the Globalnet configuration.
```

See [the Submariner docs style guide](https://submariner.io/development/website/style-guide/) and [the section on API objects in the Kubernetes docs style guide](https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects).

2024-06-18 14:00 UTC, skitt approved these changes

2024-06-18 14:30 UTC, tpantelis approved these changes

2024-06-24 15:03 UTC, dfarrell07 approved these changes

2024-06-25 12:01 UTC, vthapar approved these changes

2024-06-25 13:38 UTC, merged