Add release note for 0.14.9
submariner-io/submariner-website pull request #1158
Opened 2024-07-26 20:35 UTC by tpantelis

This release fixes 0.14.8 so also remove the section for 0.14.8.

2024-07-31 05:48 UTC, vthapar commented
@tpantelis Is this ready for review? Shows still in Draft stage.

2024-07-31 10:45 UTC, tpantelis commented
> @tpantelis Is this ready for review? Shows still in Draft stage.

I was waiting for downstream testing to succeed first in case we need to do another release but we don't have to.

2024-08-01 10:26 UTC, skitt requested changes

2024-08-01 10:26 UTC, skitt commented on src/content/community/releases/_index.en.md
> +**Note**: this version also fixes an issue with v0.14.8.
```suggestion
**Note**: this version replaces v0.14.8.
```

for consistency with other similar releases.

2024-08-01 11:58 UTC, skitt approved these changes

2024-08-01 14:30 UTC, dfarrell07 approved these changes

2024-08-01 15:08 UTC, merged