Add 0.19 release note for PR cloud prepare #1007
submariner-io/submariner-website pull request #1192
Opened 2024-10-08 18:00 UTC by aswinsuryan

Add 0.19 release note for PR [cloud prepare#1007](https://github.com/submariner-io/cloud-prepare/pull/1007)

2024-10-08 18:27 UTC, tpantelis requested changes

2024-10-08 18:27 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +* New options are added in cloud prepare to support custom vpc in AWS
```suggestion
* New options were added to `subctl cloud prepare` to support a custom vpc for AWS.
```

2024-10-08 23:45 UTC, tpantelis approved these changes

2024-10-09 08:58 UTC, skitt approved these changes

2024-10-09 14:30 UTC, merged