Add KubeVirt clusters support for 0.19.0 release notes
submariner-io/submariner-website pull request #1200
Opened 2024-10-31 10:13 UTC by yboaron

2024-10-31 12:33 UTC, tpantelis requested changes

2024-10-31 12:33 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +* Submariner can now be deployed on K8S KubeVirt clusters (K8S nodes == KubeVirt VMs).
I'm not sure it's clear what `(K8S nodes == KubeVirt VMs)` means.

```suggestion
* Submariner can now be deployed on Kubernetes KubeVirt clusters.
```

2024-10-31 13:23 UTC, tpantelis approved these changes

2024-11-04 14:03 UTC, vthapar approved these changes

2024-11-11 16:38 UTC, merged