Add info about Round Robin ClusterIP selection
submariner-io/submariner-website pull request #250
Opened 2020-08-20 09:05 UTC by aswinsuryan

Signed-off-by: Aswin Surayanarayanan <asuryana@redhat.com>

2020-08-20 14:39 UTC, nyechiel requested changes

2020-08-20 14:39 UTC, nyechiel commented on src/content/architecture/service-discovery/_index.en.md
> +DNS Server uses a Round Robin algorithm to select the clusterIP to be returned, thus ensuring that the
```suggestion
DNS server uses a Round Robin algorithm to select the clusterIP to be returned, thus ensuring that the
```

2020-08-20 14:39 UTC, nyechiel commented on src/content/architecture/service-discovery/_index.en.md
> +the load is distributed evenly across clusters
```suggestion
load is distributed evenly across clusters.
```

2020-08-21 05:56 UTC, nyechiel approved these changes

2020-08-24 09:28 UTC, vthapar requested changes

2020-08-24 09:28 UTC, vthapar commented on src/content/architecture/service-discovery/_index.en.md
> +DNS server uses a round robin algorithm for IP selection to distribute the load evenly across the clusters.
```suggestion
Lighthouse DNS server uses a round robin algorithm for IP selection to distribute the load evenly across the clusters.
```

2020-08-26 14:14 UTC, vthapar approved these changes

2020-08-26 14:48 UTC, merged