Rebuild all the content, including stable branches
submariner-io/submariner-website pull request #416
Opened 2021-01-14 15:13 UTC by mangelajo

This will render the master version on the base of the
website "/", while stable releases will be rendered as:

 /0.8/ /0.9/ /0.10/ ... etc ..

Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

2021-01-14 15:22 UTC, mangelajo commented on .github/workflows/publish.yml
> +        run: make all-static
static-all

2021-01-14 15:38 UTC, tpantelis approved these changes

2021-01-14 15:38 UTC, tpantelis approved these changes

2021-01-14 15:41 UTC, nyechiel approved these changes

2021-01-14 17:02 UTC, skitt requested changes
A few improvements to the script ;-).

2021-01-14 17:02 UTC, skitt commented on scripts/make-all-versions
> +set -x
```suggestion
set -ex
```

2021-01-14 17:02 UTC, skitt commented on scripts/make-all-versions
> +    VERSION=$(echo $release | cut -d- -f 2)
```suggestion
    VERSION=${release#release-}
```

2021-01-15 09:38 UTC, mangelajo commented
Letting CI run, then I'll squash locally

2021-01-15 09:50 UTC, mangelajo commented
@skitt I reverted the refname:short part, as for some reason it seems to fail on the github checkout:

https://github.com/submariner-io/submariner-website/pull/416/checks?check_run_id=1707652749#step:3:38

2021-01-15 13:32 UTC, skitt approved these changes

2021-01-15 13:32 UTC, merged