Update release documentation for stable branches
submariner-io/submariner-website pull request #430
Opened 2021-01-26 14:25 UTC by mkolesnik

Now that the automated release process can create the stable brnaches,
update the documentation accordingly.

Depends on: https://github.com/submariner-io/releases/pull/85

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2021-01-26 14:33 UTC, mangelajo approved these changes

2021-01-26 17:07 UTC, dfarrell07 requested changes

2021-01-26 17:07 UTC, dfarrell07 commented on src/content/development/release-process/_index.en.md
> +any other minor release will all be maintained and released on the `release-0.8` branch.
```suggestion
any other minor releases will all be maintained and released on the `release-0.8` branch.
```

2021-01-26 17:07 UTC, dfarrell07 commented on src/content/development/release-process/_index.en.md
> +The automated release process, which is described henceforth, can also create these stable branches when necessary.
```suggestion
The automated release process described here can also create these stable branches when necessary.
```

2021-01-26 17:07 UTC, dfarrell07 commented on src/content/development/release-process/_index.en.md
> +In case you're creating a new stable release, the release automation process can create the stable branches. To do so,
```suggestion
If you're creating a new stable release, the release automation process can create the stable branches. To do so,
```

2021-02-11 19:53 UTC, mangelajo commented
@mkolesnik check the comments ^

2021-02-19 20:47 UTC, dfarrell07 requested changes

2021-02-19 20:47 UTC, dfarrell07 commented on src/content/development/release-process/_index.en.md
> +2) Create a new file in the `releases` directory (you can copy the `example.yaml file`). For our example, we'll name it `v0.8.0.yaml`.
```suggestion
2) Create a new file in the `releases` directory (you can copy the `example.yaml` file). For our example, we'll name it `v0.8.0.yaml`.
```

2021-02-19 20:47 UTC, dfarrell07 commented on src/content/development/release-process/_index.en.md
> +any other minor releases will all be maintained and released on the `release-0.8` branch.
```suggestion
Stable branches will be maintained for major and minor versions. For example, versions v0.8.0, v0.8.1 and
any other 0.8.x releases will all be maintained and released on the `release-0.8` branch.
```

2021-02-25 06:02 UTC, nyechiel commented
@mkolesnik can you please address the review comments?

2021-02-25 13:34 UTC, nyechiel approved these changes

2021-03-08 17:51 UTC, dfarrell07 approved these changes

2021-03-08 17:52 UTC, merged