ServiceExport changes for Globalnet
submariner-io/submariner-website pull request #449
Opened 2021-02-17 10:59 UTC by vthapar

Services running in a Globalnet deployment now require a ServiceExport
to be annotated with GlobalIP. Services that are not exported, will not
be reachable across clusters anymore.

Fixes #434 

Signed-off-by: Vishal Thapar <5137689+vthapar@users.noreply.github.com>

2021-02-17 15:48 UTC, nyechiel approved these changes
LGTM. @sridhargaddam can you also take a look at this please?

2021-02-17 17:50 UTC, sridhargaddam commented on src/content/getting-started/architecture/globalnet/_index.en.md
> +* On deletion of a Pod, Service or ServiceExport, releases its globalIp back to the pool.
Can you also update line 72 to include "Service or ServiceExport"

2021-02-19 14:53 UTC, tpantelis requested changes

2021-02-19 14:53 UTC, tpantelis commented on src/content/getting-started/architecture/globalnet/_index.en.md
> +This globalIp is used for allcross-cluster communication to and from a Pod and the globalIp of a
```suggestion
This globalIp is used for all cross-cluster communication to and from a Pod and the globalIp of a
```

2021-02-24 15:19 UTC, nyechiel commented
@vthapar can you please address the review comments?

2021-02-25 06:00 UTC, nyechiel approved these changes

2021-02-25 06:04 UTC, sridhargaddam approved these changes

2021-03-01 16:30 UTC, dfarrell07 commented on src/content/getting-started/architecture/globalnet/_index.en.md
> +* On deletion of Pod, Service or ServiceExport, clean up the rules from the gateway node.
```suggestion
* Clean up the rules from the gateway node on the deletion of a Pod, Service, or ServiceExport.
```

2021-03-03 16:31 UTC, nyechiel commented
@tpantelis you requested changes on this one, can you please review again?

2021-03-03 17:25 UTC, tpantelis approved these changes

2021-03-03 17:25 UTC, merged