WIP: docs: add quickstart guide for k3s
submariner-io/submariner-website pull request #454
Opened 2021-02-25 19:21 UTC by mkimuram

Closes: #453

2021-02-25 19:24 UTC, mkimuram commented
@mangelajo 

This might need to wait for 0.9 release, because 
- k3s requires network plugin detection fix (already merged in devel branch),
- Wait for change in `--natt=false` options from `--disable-nat`

However, making PR to get feedback early.

2021-03-09 19:12 UTC, dfarrell07 requested changes
Thanks @mkimuram! A few minor suggestions inline. Otherwise it looks good from a docs prospective, although I haven't actually run through the steps.

2021-03-09 19:12 UTC, dfarrell07 commented on src/content/getting-started/quickstart/k3s/_index.md
> +weight: 10
Let's make this weight 15 (or 20 and bump the current 20/30 by 10) so it comes after the KIND sandbox/CI environment in the left nav bar list. I think that's our recommended "default path" for folks.

2021-03-09 19:12 UTC, dfarrell07 commented on src/content/getting-started/quickstart/k3s/_index.md
> +title: "k3s"
```suggestion
title: "K3s"
```

It seems like it's generally capitalized in the project's docs? https://github.com/k3s-io/k3s

(applies elsewhere)

2021-04-04 13:59 UTC, nyechiel commented
@mkimuram can you please address the review comments? Let's get it merged :)

2021-04-05 19:15 UTC, mkimuram commented
@nyechiel 

Thank you for your reminder. 

@dfarrell07

Thank you for your review and sorry for late response.
Fixed. PTAL

2021-04-07 03:03 UTC, dfarrell07 approved these changes

2021-04-07 06:21 UTC, nyechiel approved these changes

2021-04-07 11:52 UTC, tpantelis requested changes

2021-04-07 11:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +This quickstart guide covers the necessary steps to deploy two [K3s](https://k3s.io/) cluslters
```suggestion
This quickstart guide covers the necessary steps to deploy two [K3s](https://k3s.io/) clusters
```

2021-04-07 11:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +2. Decide the Pod CIDR and the Service CIDR for each K3s cluster.
```suggestion
2. Choose the Pod CIDR and the Service CIDR for each K3s cluster.
```

2021-04-07 11:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +|10.44.0.0/16  |10.45.0.0/16  |
In  the Prerequisites, we instruct the user to choose the CIDRs but here we're telling them to use specific CIDRs.

2021-04-07 11:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +In this step you will deploy **cluster-a** on node-a using the the following IP ranges:
```suggestion
In this step you will deploy **cluster-a** on node-a using the the following CIDR:
```

2021-04-07 11:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +To deploy K3s with the IP ranges, run below commands on node-a.
```suggestion
To deploy K3s with the CIDRs, run the following commands on node-a.
```

2021-04-07 11:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +If the IP should be different from the first field of `hostname -I`, modify the value manually.
```suggestion
The kubeconfig file needs to be modified to set the Kubernetes API endpoint point to the public IP the node-a,
which is obtained from the first field yielded by `hostname -I`.
```

2021-04-07 11:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +In this step you will deploy **cluster-b** on node-b using the the following IP ranges:
```suggestion
In this step you will deploy **cluster-b** on node-b using the the following CIDRs:
```

2021-04-07 11:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +To deploy K3s with the IP ranges, run below commands on node-b.
```suggestion
To deploy K3s with the CIDRs, run the following commands on node-b.
```

2021-04-07 11:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +If the IP should be different from the first field of `hostname -I`, modify the value manually.
```suggestion
The kubeconfig file needs to be modified to set the Kubernetes API endpoint point to the public IP the node-a,
which is obtained from the first field yielded by `hostname -I`.
```

2021-04-07 11:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +Then, copy kubeconfig.cluster-b to node-a.
```suggestion
Next, copy kubeconfig.cluster-b to node-a.
```

2021-04-07 11:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +#### Use cluster-a as Broker
```suggestion
#### Use cluster-a as the Broker
```

2021-04-07 11:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +On node-a, run the below command.
```suggestion
On node-a, run:
```

2021-04-07 11:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +```
I think we can reduce these sections.

#### Join cluster-a to the Broker

```bash
subctl join --kubeconfig kubeconfig.cluster-a broker-info.subm --clusterid cluster-a --natt=false
```

#### Join cluster-b to the Broker

```bash
subctl join --kubeconfig kubeconfig.cluster-b broker-info.subm --clusterid cluster-b --natt=false
```

2021-04-07 11:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +You now have a Submariner environment that you can experiment with.
I don't think we need this statement.

```suggestion
```

2021-04-07 13:41 UTC, mkimuram commented
@tpantelis 

Thank you for your review. Fixed as suggested. 

> In the Prerequisites, we instruct the user to choose the CIDRs but here we're telling them to use specific CIDRs.

The third commit addresses this. Please check if it is OK.

2021-04-07 14:52 UTC, tpantelis requested changes

2021-04-07 14:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +To deploy K3s with the CIDRs, run the following commands on node-a.
```suggestion
In this step you will deploy K3s on node-a using the the **cluster-a** CIDRs.
```

2021-04-07 14:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +The kubeconfig file needs to be modified to set the Kubernetes API endpoint to the public IP of the node-a,
```suggestion
The kubeconfig file needs to be modified to set the Kubernetes API endpoint to the public IP of node-a,
```

2021-04-07 14:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +To deploy K3s with the CIDRs, run the following commands on node-b.
```suggestion
In this step you will deploy K3s on node-b using the the **cluster-b** CIDRs.
```

2021-04-07 14:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +The kubeconfig file needs to be modified to set the Kubernetes API endpoint to the public IP of the node-b,
```suggestion
The kubeconfig file needs to be modified to set the Kubernetes API endpoint to the public IP of node-b,
```

2021-04-07 14:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +Join cluster-a to the Broker
I think it's simpler to just make this its own section - avoids repeating "Join cluster-a ...".

```suggestion
#### Join cluster-a to the Broker
```

2021-04-07 14:52 UTC, tpantelis commented on src/content/getting-started/quickstart/k3s/_index.md
> +Join cluster-b to the Broker
```suggestion
#### Join cluster-b to the Broker
```

2021-04-07 15:41 UTC, mkimuram commented
@tpantelis 

Thank you for your review. Fixed and squashed the commit.

2021-04-07 15:44 UTC, tpantelis approved these changes

2021-04-07 15:45 UTC, merged