add a note about wireguard default port
submariner-io/submariner-website pull request #463
Opened 2021-03-12 12:26 UTC by kubicgruenfeld

added a short note about the default wireguard

2021-03-12 12:56 UTC, tpantelis requested changes, later dismissed

2021-03-12 12:56 UTC, tpantelis commented on src/content/getting-started/_index.en.md
> +IPsec are 4500/UDP and 500/UDP. The wireguard cable drive also use 4500/UDP.
```suggestion
IPsec are 4500/UDP and 500/UDP and by wireguard, 4500/UDP.
```

2021-03-15 09:13 UTC, mangelajo approved these changes
Thank you very much for the contribution!

2021-03-15 10:03 UTC, skitt approved these changes

2021-03-23 02:18 UTC, dfarrell07 approved these changes

2021-03-23 02:19 UTC, merged

2021-03-23 02:20 UTC, dfarrell07 commented
Thanks @kubicgruenfeld!