Add licensing information
submariner-io/submariner-website pull request #531
Opened 2021-06-09 11:58 UTC by skitt

This documents the licenses we expect, and the exact header which our
CI checks for.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

2021-06-09 12:16 UTC, Jaanki approved these changes

2021-06-09 13:13 UTC, dfarrell07 requested changes

2021-06-09 13:13 UTC, dfarrell07 commented on src/content/development/licenses/_index.en.md
> +weight: 5
```suggestion
weight: 35
```

To put it in ABC order.

2021-06-09 15:32 UTC, dfarrell07 approved these changes

2021-06-10 12:12 UTC, nyechiel approved these changes

2021-06-10 16:04 UTC, tpantelis approved these changes

2021-06-10 20:57 UTC, tpantelis commented
hmm... there's 4 approvals with one code owner (me) so why does it say "Merging can be performed automatically with 2 approving reviews." ...

2021-06-16 09:27 UTC, mkolesnik approved these changes

2021-06-16 09:27 UTC, merged

2021-06-16 09:28 UTC, mkolesnik commented
> hmm... why does it require a review from code owner @mkolesnik ... I'm a code owner (or should be) so that should be enough...

seems it likes me :)