Document known issue for vxlan metrics
submariner-io/submariner-website pull request #553
Opened 2021-07-06 14:38 UTC by maayanf24

Gateway metrics rx/tx will not be collected when using vxlan
cable-driver

Signed-off-by: Maayan Friedman <maafried@redhat.com>

2021-07-06 15:14 UTC, skitt requested changes
Minor tweak. We use “cable driver” throughout the docs.

2021-07-06 15:14 UTC, skitt commented on src/content/operations/known-issues/_index.en.md
> +* Submariner Gateway metrics `submariner_gateway_rx_bytes` and `submariner_gateway_tx_bytes` will not be collected when using cable-driver VXLAN.
```suggestion
* Submariner Gateway metrics `submariner_gateway_rx_bytes` and `submariner_gateway_tx_bytes` will not be collected when using the VXLAN cable driver.
```

2021-07-06 15:40 UTC, nyechiel commented on src/content/operations/known-issues/_index.en.md
> +## VXLAN
Also, I don't think that VXLAN needs its our section. I suggest to use the "General" section above

2021-07-07 07:29 UTC, nyechiel approved these changes

2021-07-07 13:34 UTC, aswinsuryan approved these changes

2021-07-09 09:43 UTC, skitt approved these changes

2021-07-09 09:44 UTC, merged