Document `make release` automated process
submariner-io/submariner-website pull request #560
Opened 2021-07-13 12:01 UTC by mkolesnik

Added documentation for the usage of `make release` and updated some
parts in the document to incorporate it.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2021-07-13 12:06 UTC, tpantelis requested changes

2021-07-13 12:06 UTC, tpantelis commented on src/content/development/release-process/_index.en.md
> +Make sure to specify the proper version you're intenting to release (e.g. for rc0 specify `VERSION="0.8.0-rc0"`).
```suggestion
Make sure to specify the proper version you're intending to release (e.g. for rc0 specify `VERSION="0.8.0-rc0"`).
```

2021-07-14 15:21 UTC, tpantelis approved these changes

2021-07-27 14:34 UTC, dfarrell07 approved these changes

2021-07-27 14:35 UTC, merged