Add release notes for v0.9.1
submariner-io/submariner-website pull request #562
Opened 2021-07-21 10:02 UTC by Jaanki

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

2021-07-21 12:27 UTC, SteveMattar approved these changes

2021-07-21 13:04 UTC, mkolesnik approved these changes

2021-07-21 13:07 UTC, nyechiel requested changes

2021-07-21 13:07 UTC, nyechiel commented on src/content/community/releases/_index.en.md
> +* Fixed --kubecontext in subctl commands and now it properly works as it used to.
```suggestion
* Fixed --kubecontext in `subctl` commands and now it properly works as it used to.
```

2021-07-21 13:07 UTC, nyechiel commented on src/content/community/releases/_index.en.md
> +* Simplified `subctl cloud prepare aws` to extract credentials, infra id and region from local configuration field (if available).
```suggestion
* Simplified `subctl cloud prepare aws` to extract credentials, infra id and region from local configuration file (if available).
```

2021-07-21 13:07 UTC, nyechiel commented on src/content/community/releases/_index.en.md
> +* Fixed support to set natt-discovery-port and udp-port via node annotations.
What do you mean "fixed support"?

2021-07-22 17:48 UTC, tpantelis requested changes

2021-07-22 17:48 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +* Fixed --kubecontext in subctl commands and now it properly works as it used to.
```suggestion
* The `--kubecontext` flag in `subctl` commands now works properly.
```

2021-07-22 17:48 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +* Simplified `subctl cloud prepare aws` to extract credentials, infra id and region from local configuration field (if available).
```suggestion
* Simplified `subctl cloud prepare aws` to extract the credentials, infra id and region from a local configuration file (if available).
```

2021-07-23 12:36 UTC, tpantelis requested changes

2021-07-23 12:36 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +* natt-discovery-port and udp-port can now be set via node annotations.
```suggestion
* The `natt-discovery-port` and `udp-port` options can now be set via node annotations.
```

2021-07-26 11:28 UTC, tpantelis approved these changes

2021-07-26 11:30 UTC, nyechiel approved these changes

2021-07-26 11:30 UTC, merged