Add details about SRV record in user guide
submariner-io/submariner-website pull request #564
Opened 2021-07-23 12:02 UTC by aswinsuryan

Signed-off-by: Aswin Surayanarayanan <asuryana@redhat.com>

2021-07-28 18:57 UTC, dfarrell07 requested changes
Looks good, a few style nits inline.

2021-07-28 18:57 UTC, dfarrell07 commented on src/content/operations/usage/_index.en.md
> +The following commands create an `nginx` Service in the nginx-test namespace which targets TCP port 8080, with name http, on any Pod with the
```suggestion
The following commands create an `nginx` Service in the `nginx-test` namespace which targets TCP port 8080, with name http, on any Pod with the
```

Namespaces should be in `code style`.

https://kubernetes.io/docs/contribute/style/style-guide/#use-code-style-for-object-field-names-and-namespaces

2021-07-28 18:57 UTC, dfarrell07 commented on src/content/operations/usage/_index.en.md
> +(also called ClusterIP):
```suggestion
(also called ClusterIP):
```

Is this an API object? If so, it should be `code style`.

https://kubernetes.io/docs/contribute/style/style-guide/#code-style-inline-code

2021-07-28 18:57 UTC, dfarrell07 commented on src/content/operations/usage/_index.en.md
> +`kubectl apply` the following yaml within the nginx-test namespace to create the service:
```suggestion
`kubectl apply` the following YAML within the `nginx-test` namespace to create the service:
```

2021-07-28 18:57 UTC, dfarrell07 commented on src/content/operations/usage/_index.en.md
> +`kubectl apply` the following yaml within the nginx-test namespace to create the service:
```suggestion
`kubectl apply` the following YAML within the `nginx-test` namespace to create the service:
```

2021-07-29 11:19 UTC, tpantelis approved these changes

2021-08-13 15:39 UTC, dfarrell07 approved these changes

2021-08-13 15:40 UTC, merged