Release notes for v0.10.0
submariner-io/submariner-website pull request #571
Opened 2021-08-11 03:23 UTC by tpantelis

2021-08-11 14:58 UTC, dfarrell07 requested changes

2021-08-11 14:58 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +  * The initial Globanet implementation is deprecated in favor of a new  implementation which is more performant and scalable.
```suggestion
  * The initial Globanet implementation is deprecated in favor of a new implementation which is more performant and scalable.
```

2021-08-11 15:11 UTC, dfarrell07 approved these changes

2021-08-16 13:07 UTC, skitt approved these changes

2021-08-16 13:08 UTC, merged