Document `make backport` details and usage.
submariner-io/submariner-website pull request #580
Opened 2021-09-03 03:36 UTC by Jaanki

Signed-Off-By: Janki Chhatbar <jchhatba@redhat.com>

2021-09-13 15:04 UTC, dfarrell07 commented
We don't have gitlint on this repo unfortunately, but if we did I think it would fail on the period on the first line of the commit message. Might still be best to follow those practices.

2021-09-13 15:11 UTC, dfarrell07 requested changes

2021-09-13 15:11 UTC, dfarrell07 commented on src/content/development/backports/_index.en.md
> +The script does the following:
```suggestion
Backporting a commit is automated by running:

`make backport release=<release-branch> pr=<PR to cherry-pick>`

The make target runs [`backport.sh`](https://github.com/submariner-io/shipyard/scripts/shared/backport.sh, originally developed by the Kubernetes community as [`cherry_pick_pull.sh`](https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh).

The script does the following:
```

2021-09-13 15:11 UTC, dfarrell07 commented on src/content/development/backports/_index.en.md
> +3. `GITHUB_USER` needs to be set to your `GitHub username`.
```suggestion
3. `GITHUB_USER` needs to be set to your GitHub username.
```

2021-09-14 12:38 UTC, tpantelis requested changes

2021-09-14 12:38 UTC, tpantelis commented on src/content/development/backports/_index.en.md
> +4. Multiple PRs can be cherry-picked together by passing the comma-separated list of PRs to be cherry-picked like `pr=<PR1,PR2>`.
```suggestion
1. Cherry-picks the commits from the PR onto <remote branch>.
2. Creates a PR on `<release-branch>` with the title `Automated backport of <original PR number>: <original PR title>`.
3. Adds the `backport-handled` label to the original PR.

The DRY_RUN environment variable can be set to skip creating the PR. When set, it leaves you in a branch containing the commits that were cherry-picked.

Multiple PRs can be backported together by passing a comma-separated list of PR numbers, eg `pr=630,631`.   
```

2021-09-14 12:38 UTC, tpantelis commented on src/content/development/backports/_index.en.md
> +2. Remote for your forked repository, `FORK_REMOTE`  is set to `GITHUB_USER`.
```suggestion
The script uses the following environment variables. Please change them according to your setup.
* `UPSTREAM_REMOTE`: the remote for the upstream repository. Defaults to `origin`.
* `FORK_REMOTE`: the remote for your forked repository. Defaults to `GITHUB_USER`.
* `GITHUB_USER`: needs to be set to your GitHub username.
```

2021-09-22 12:02 UTC, tpantelis requested changes
Just a few more minor things.

2021-09-22 12:02 UTC, tpantelis commented on src/content/development/backports/_index.en.md
> +Backporting a commit is automated by running:
```suggestion
Backporting a pull request (PR) is automated by running:
```

2021-09-22 12:02 UTC, tpantelis commented on src/content/development/backports/_index.en.md
> +and has been reused, and edited to suit the needs, from [their repo](https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh).
```suggestion
[backport.sh](https://github.com/submariner-io/shipyard/scripts/shared/backport.sh), originally developed by the [Kubernetes community](https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh).
```

2021-09-22 12:02 UTC, tpantelis commented on src/content/development/backports/_index.en.md
> +1. Cherry-picks the commits from the PR onto <remote branch>.
```suggestion
1. Cherry-picks the commits from the PR onto `<remote branch>`.
```

2021-09-22 12:02 UTC, tpantelis commented on src/content/development/backports/_index.en.md
> +3. Adds the `backport-handled` label to the original PR and `automated-backport` label to the backported PR.
```suggestion
3. Adds the `backport-handled` label to the original PR and the `automated-backport` label to the backported PR.
```

2021-09-22 12:47 UTC, tpantelis approved these changes

2021-09-22 18:06 UTC, dfarrell07 approved these changes

2021-09-22 18:39 UTC, merged