Add release notes for v0.11.0-rc0
submariner-io/submariner-website pull request #591
Opened 2021-10-06 12:40 UTC by Jaanki

Signed-Off-By: Janki Chhatbar <jchhatba@redhat.com>

2021-10-06 13:07 UTC, tpantelis requested changes

2021-10-06 13:07 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +* `--ignore-requirements` flag is added to `subctl join` command which ignores Submariner requirement checks.
```suggestion
* `--ignore-requirements` flag was added to `subctl join` command which ignores Submariner requirement checks.
```

2021-10-06 13:09 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +## v0.11.0-rc0
```suggestion
## v0.11.0
```

2021-10-06 13:20 UTC, skitt requested changes

2021-10-06 13:20 UTC, skitt commented on src/content/community/releases/_index.en.md
> +* `subctl cloud prepare` command now supports GCP as well as generic kubernetes clusters.
```suggestion
* `subctl cloud prepare` command now supports Google Cloud Platform as well as generic Kubernetes clusters.
```

2021-10-25 14:34 UTC, nyechiel approved these changes

2021-10-25 14:34 UTC, nyechiel commented
@Jaanki can you fix DCO here?

2021-10-26 03:03 UTC, tpantelis approved these changes

2021-10-26 11:54 UTC, Jaanki commented
> @Jaanki can you fix DCO here?

@nyechiel DOne

2021-10-26 11:55 UTC, nyechiel approved these changes

2021-10-26 12:40 UTC, sridhargaddam approved these changes

2021-10-28 13:38 UTC, skitt approved these changes

2021-10-28 13:38 UTC, merged