Document usage of YAML settings
submariner-io/submariner-website pull request #609
Opened 2021-11-08 13:55 UTC by mkolesnik

Since we're switching to YAML Shipyard settings, which are much
friendlier, document the usage of those settings.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2021-11-08 15:18 UTC, skitt requested changes, later dismissed

2021-11-08 15:18 UTC, skitt commented on src/content/development/shipyard/advanced/_index.en.md
> +* **submariner**: If Submariner should ber deployed, set to `true`. Otherwise, leave unset (or set to `false` explicitly).
```suggestion
* **submariner**: If Submariner should be deployed, set to `true`. Otherwise, leave unset (or set to `false` explicitly).
```

2021-11-10 12:17 UTC, dfarrell07 approved these changes

2021-11-15 08:35 UTC, skitt approved these changes

2021-11-15 08:36 UTC, merged