Use year/month date format in reference links
submariner-io/submariner-website pull request #661
Opened 2022-01-27 17:04 UTC by dfarrell07

For the dates we include alongside each link to an external reference
about Submariner, use the more standard year/month format. This is more
clear to sort and more common internationally.

Depends on https://github.com/submariner-io/submariner-website/pull/660.

2022-01-27 17:19 UTC, skitt requested changes
I’m not sure about “more common internationally” — I’ve rarely seen dates in YYYY/MM format. As far as standards go, ISO-8601 says “YYYY-MM” ;-).

I suspect that most people would find explicit month names easier to read, “October 2021”, “May 2021” etc., but that’s harder to sort.

2022-01-27 17:58 UTC, dfarrell07 commented
There are some docs here about what's common where:

https://calendars.fandom.com/wiki/Date_format_by_country

Learning from that, what I had in mind is that it's unusual to do Middle-endian as we do in the US, but that doesn't show up when only using months and days.

We can use dashes instead of slashes and follow ISO 8601, and I'll remove the reasoning about "common" from the commit message. I can also note that we follow ISO 8601 in the Docs Style Guide.

2022-01-29 17:00 UTC, nyechiel approved these changes
Very American, but as long as we are consistent, +1.

2022-01-31 08:21 UTC, skitt approved these changes

2022-01-31 08:31 UTC, sridhargaddam approved these changes

2022-01-31 10:13 UTC, merged