Doc avoiding "new" in Website Style Guide
submariner-io/submariner-website pull request #705
Opened 2022-03-10 15:38 UTC by dfarrell07

Use versions instead of "new" for less maintenance.

Document this practice in the style guide for clarity and consistency.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

2022-03-10 15:42 UTC, skitt requested changes

2022-03-10 15:42 UTC, skitt commented on src/content/development/website/style-guide/_index.en.md
> +Instead, document the versions that support things.
```suggestion
Instead, document the versions that introduce or remove features:

> As of 0.12.0, a `subctl` image is provided ...
```

2022-03-11 12:14 UTC, skitt approved these changes

2022-03-13 08:42 UTC, maayanf24 approved these changes

2022-03-13 09:37 UTC, mkolesnik approved these changes

2022-03-14 08:25 UTC, merged