Document known issue regarding Globalnet metrics
submariner-io/submariner-website pull request #713
Opened 2022-03-17 07:25 UTC by maayanf24

Fixes #703

Signed-off-by: Maayan Friedman <maafried@redhat.com>

2022-03-17 12:15 UTC, skitt requested changes

2022-03-17 12:15 UTC, skitt commented on src/content/operations/known-issues/_index.en.md
> +* On OpenShift, Globalnet metrics do not show up. This can be done manually by open the Globalnet metrics port, 8081.
```suggestion
* On OpenShift, Globalnet metrics do not show up. This can be done manually by opening the Globalnet metrics port, 8081.
```

2022-03-17 17:27 UTC, sridhargaddam requested changes

2022-03-17 17:27 UTC, sridhargaddam commented on src/content/operations/known-issues/_index.en.md
> +* On OpenShift, Globalnet metrics do not show up. This can be done manually by opening the Globalnet metrics port, 8081.
```suggestion
* On OpenShift, Globalnet metrics do not show up. This can be done manually by opening the Globalnet metrics port, TCP/8081.
```

2022-03-18 13:39 UTC, tpantelis approved these changes

2022-03-21 08:41 UTC, sridhargaddam approved these changes

2022-03-22 15:57 UTC, dfarrell07 approved these changes

2022-03-30 12:03 UTC, nyechiel requested changes
Sorry I am late, but I don't think the text here is clear. When and how this port should be opened exactly? 

As an e.g, [here](https://submariner.io/getting-started/#prerequisites) we have clearer instructions that say: "Submariner uses TCP port 8080 to export metrics on the Gateway nodes. Ensure that firewall configuration allows ingress 8080/TCP on the Gateway nodes so that other nodes in the cluster can access it. Also, no other workload on the Gateway nodes should be listening on TCP port 8080." 

While on this, we also need to update the prerequisite section shown above and mention that Submariner uses TCP/8081 for Globalnet metrics. This can be done on a separate PR, let's just not forget about it.

2022-05-09 19:14 UTC, dfarrell07 commented
@nyechiel Can you re-review this one?

2022-05-10 09:24 UTC, nyechiel approved these changes

2022-05-10 09:25 UTC, nyechiel commented
@maayanf24 LGTM now, but there is a Markdown issue that needs to be fixed.

2022-05-11 07:40 UTC, maayanf24 commented
> @maayanf24 LGTM now, but there is a Markdown issue that needs to be fixed.

The Markdown issue is related to "unsafe repository". @dfarrell07 - what are the steps to solve this?

2022-05-11 09:51 UTC, skitt commented on src/content/operations/known-issues/_index.en.md
> +that nodes should be listening on TCP port 8081.
Sorry, I missed this one:

```suggestion
those nodes should be listening on TCP port 8081.
```

2022-05-11 09:51 UTC, skitt requested changes
Small grammar fix…

2022-05-11 10:31 UTC, maayanf24 commented on src/content/operations/known-issues/_index.en.md
> +that nodes should be listening on TCP port 8081.
fixed

2022-05-11 13:43 UTC, skitt approved these changes

2022-05-11 13:43 UTC, merged