[Release Guide] Document Sprints section
submariner-io/submariner-website pull request #717
Opened 2022-03-17 12:19 UTC by mkolesnik

Depends on: #711 

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-03-21 16:45 UTC, skitt requested changes

2022-03-21 16:45 UTC, skitt commented on src/content/development/contribution-guide/_index.en.md
> +Specific sprints and their contents are details in the following sections.
```suggestion
Specific sprints and their contents are detailed in the following sections.
```

2022-03-21 16:45 UTC, skitt commented on src/content/development/contribution-guide/_index.en.md
> +Each sprint starts and ends on a boundry day, when one sprint ends another one begins.
```suggestion
Each sprint starts and ends on a boundary day, when one sprint ends another one begins.
```

2022-03-21 16:45 UTC, skitt commented on src/content/development/contribution-guide/_index.en.md
> +The boundry day is **Monday**.
```suggestion
The boundary day is **Monday**.
```

2022-03-21 16:45 UTC, skitt commented on src/content/development/contribution-guide/_index.en.md
> +On the sprint boundry day we will:
```suggestion
On the sprint boundary day we will:
```

2022-03-21 16:45 UTC, skitt commented on src/content/development/contribution-guide/_index.en.md
> +* Perform a milestone release (When applicable).
```suggestion
* Perform a milestone release (when applicable).
```

2022-03-22 09:53 UTC, mkolesnik commented
Updated according to fixes and also added a paragraph about test days.

2022-03-22 09:55 UTC, skitt approved these changes

2022-03-22 15:55 UTC, dfarrell07 approved these changes

2022-03-22 16:45 UTC, tpantelis requested changes

2022-03-22 16:45 UTC, tpantelis commented on src/content/development/contribution-guide/_index.en.md
> +Most sprints will end with a milestone pre-release, the designation of which is detailed in the following sections.
```suggestion
Most sprints will end with a milestone pre-release as detailed in the following sections.
```

2022-03-22 16:45 UTC, tpantelis commented on src/content/development/contribution-guide/_index.en.md
> +For most sprints a [test day](#test-days) to test the pre-release will be held after its creation.
```suggestion
A formal [test day](#test-days) may be held to facilitate testing of the pre-release.
```

2022-03-22 16:45 UTC, tpantelis commented on src/content/development/contribution-guide/_index.en.md
> +Each sprint starts and ends on a boundary day, when one sprint ends another one begins.
```suggestion
Each sprint ends on a boundary day which also marks the beginning of the next sprint.
```

2022-03-22 16:45 UTC, tpantelis commented on src/content/development/contribution-guide/_index.en.md
> +The boundary day is **Monday**.
```suggestion
The boundary days occur on a **Monday**.
```

2022-03-23 07:31 UTC, mkolesnik commented
Thanks for the suggestions, please make sure to squash before merging!

2022-03-23 12:11 UTC, tpantelis approved these changes

2022-03-23 12:24 UTC, merged