[Release Guide] Document Test Days
submariner-io/submariner-website pull request #739
Opened 2022-04-06 12:59 UTC by mkolesnik

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-04-06 13:38 UTC, Jaanki requested changes

2022-04-06 13:38 UTC, Jaanki commented on src/content/development/contribution-guide/_index.en.md
> +The goals of these days are:
```suggestion
The goals of these days are to:
```

2022-04-06 13:38 UTC, Jaanki commented on src/content/development/contribution-guide/_index.en.md
> +* Creating a test day document, if one doesn't exist yet.
```suggestion
* Creating a test day spreadsheet, if one doesn't exist yet by Using the [test day template].
```

2022-04-06 13:38 UTC, Jaanki commented on src/content/development/contribution-guide/_index.en.md
> +  * Using the [test day template].
Merged with above point.

2022-04-12 16:09 UTC, dfarrell07 approved these changes

2022-04-12 16:09 UTC, dfarrell07 commented on src/content/development/contribution-guide/_index.en.md
> +The goals of these days are:
IMHO it's okay as-is

2022-04-12 16:09 UTC, dfarrell07 commented on src/content/development/contribution-guide/_index.en.md
> +* Validate any [bugs](#bugs) that were fixed were actually fixed.
```suggestion
* Validate any [bugs](#bugs) that were closed were actually fixed.
```

2022-05-10 07:50 UTC, maayanf24 approved these changes

2022-05-11 13:51 UTC, dfarrell07 commented
@Jaanki Can you re-review?

2022-05-19 04:38 UTC, Jaanki approved these changes

2022-05-19 10:43 UTC, merged