Tweak 0.12 release notes
submariner-io/submariner-website pull request #740
Opened 2022-04-11 15:54 UTC by dfarrell07

Very minor edits, including code style for a command and a grammar fix.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

2022-04-11 15:57 UTC, skitt requested changes

2022-04-11 15:57 UTC, skitt commented on src/content/community/releases/_index.en.md
> +* Added support for Globalnet objects verification using `subctl diagnose` command.
```suggestion
* Added support for Globalnet objects verification using the `subctl diagnose` command.
```

2022-04-11 16:58 UTC, tpantelis approved these changes

2022-04-12 07:25 UTC, maayanf24 approved these changes

2022-04-12 07:59 UTC, nyechiel approved these changes

2022-04-12 10:44 UTC, skitt approved these changes

2022-04-12 10:44 UTC, merged