Add information about releasing stable branches
submariner-io/submariner-website pull request #783
Opened 2022-06-23 09:17 UTC by mkolesnik

Since the release process changed in 0.13, add information on the
website clarifying the release needs to happen on the stable branch.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-06-23 14:49 UTC, skitt approved these changes

2022-06-23 16:22 UTC, tpantelis requested changes

2022-06-23 16:22 UTC, tpantelis commented on src/content/development/release-process/_index.en.md
> +branch you're releasing for (`release-<major>.<minor>`).
```suggestion
Starting with 0.13, when creating a release for a stable version (`release-<major>.<minor>`), the `make release` commands must be run on a branch based off the associated stable release branch.
```

2022-06-28 15:17 UTC, dfarrell07 approved these changes

2022-06-28 18:34 UTC, sridhargaddam approved these changes

2022-06-29 16:11 UTC, tpantelis approved these changes

2022-06-29 16:12 UTC, merged