Set latest tag to devel
submariner-io/submariner-website pull request #786
Opened 2022-06-27 15:42 UTC by tomer-shefler

2022-06-28 04:58 UTC, dfarrell07 requested changes
Good catch, thanks!

CNCF projects require a Developer Certificate of Origin sign-off for all commits, which our linter is flagging as missing. You'll need to add a `Signed-off-by` line to your commit, which git can handle for you.

```
git commit --amend -s
```

2022-07-14 12:47 UTC, dfarrell07 commented
Hey @tomer-shefler! Any questions about the DCO sign-off? Would love to get this merged.

2022-07-18 13:07 UTC, dfarrell07 approved these changes

2022-07-21 16:49 UTC, nyechiel approved these changes

2022-07-21 16:51 UTC, merged