Few GCP edits
submariner-io/submariner-website pull request #788
Opened 2022-06-29 11:02 UTC by Jaanki

1. Add gcp-lb/_index.md to
   src/content/getting-started/quickstart/_index.en.md
2. Increase its weight so that it is after `On AWS with Globalnet`
   section

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

2022-06-29 11:11 UTC, Jaanki commented on src/content/getting-started/quickstart/openshift/gcp-lb/_index.md
> +weight: 35
Reserving `30` for `Azure`. So the layout would be `On AWS` -> `On AWS with Globalnet` -> `On Azure` -> `On GCP` -> `Hybrid ....` arranged alphabetically.

2022-06-29 17:53 UTC, dfarrell07 requested changes
A first-line of the commit message like "Add GCP to indexes, fix weights" would better match our guidelines. https://submariner.io/development/code-review/#commit-message-formatting

Also needs a manual rebase.

2022-07-01 14:56 UTC, dfarrell07 approved these changes

2022-07-04 05:46 UTC, sridhargaddam approved these changes

2022-07-04 10:26 UTC, skitt approved these changes

2022-07-04 10:31 UTC, merged