Document image overriding on Helm
submariner-io/submariner-website pull request #820
Opened 2022-08-31 11:52 UTC by mkolesnik

Add documentation for overriding specific images, and fix up
documentation for overriding all images or just the operator image.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-09-01 11:11 UTC, tpantelis requested changes

2022-09-01 11:11 UTC, tpantelis commented on src/content/operations/deployment/helm/_index.en.md
> +The examples below demonstrate how to use images a local registry. It's possible to use an online registry as well.
```suggestion
The examples below demonstrate how to use images from a local registry. It's also possible to use an online registry.
```

2022-09-06 18:44 UTC, sridhargaddam approved these changes

2022-09-06 19:55 UTC, tpantelis approved these changes

2022-09-06 19:55 UTC, merged