Adding release-notes for 0.14.0
submariner-io/submariner-website pull request #849
Opened 2022-11-07 15:23 UTC by maayanf24

Signed-off-by: Maayan Friedman <maafried@redhat.com>

2022-11-07 15:43 UTC, sridhargaddam requested changes
thanks @maayanf24.

2022-11-07 15:43 UTC, sridhargaddam commented on src/content/community/releases/_index.en.md
> +* The `subctl gather` command now includes the output from `ovn-sbctl show` which has the chassis-id to hostname mapping that can
Some text is missing in this sentence.

2022-11-07 22:18 UTC, aswinsuryan approved these changes

2022-11-08 05:40 UTC, nyechiel commented
Content LGTM, @dfarrell07 can you review for style?

2022-11-08 08:18 UTC, sridhargaddam approved these changes

2022-11-08 09:33 UTC, yboaron approved these changes

2022-11-08 09:40 UTC, dfarrell07 requested changes

2022-11-08 09:40 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +runs pods on gateway nodes and forwards http requests for metrics services to gateway and Globalnet pods running on the nodes.
```suggestion
runs pods on gateway nodes and forwards HTTP requests for metrics services to gateway and Globalnet pods running on the nodes.
```

I'll propose adding a rule to our MD lint config to standardize.

2022-11-08 09:40 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +Gateway and Globalnet pods now listen on ports 32780 and 32781 instead of well known ports 8080 and 8081 to avoid conflict with
```suggestion
Gateway and Globalnet pods now listen on ports 32780 and 32781 instead of well-known ports 8080 and 8081 to avoid conflict with
```

2022-11-08 09:40 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +* Support for simulated "air-gapped" environments has been added to kind clusters.
This is cool, but I don't think we typically document additional CI coverage as user-facing. Maybe we can add a note about how to test the feature using kind in the `join --air-gapped` option below.

2022-11-08 09:40 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +* Support was added in the Shipyard project to easily deploy Submariner with a LoadBalancer type Service in front.
Again, this is cool but I don't think we typically document CI/kind features in the release notes. We could change that practice, but that should likely be an explicit conversation.

2022-11-08 09:40 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +* Support was added in Shipyard to easily create test clusters using OCP on top of AWS.
Same comment about this being a test feature, not user-facing.

2022-11-08 09:40 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +* The flannel CNI is now properly identified during join.
```suggestion
* The Flannel CNI is now properly identified during join.
```

The usages I see are very inconsistent, I see mixed cap and non-cap in every document I checked. If the project isn't consistent, I suggest we follow normal grammar rules and cap it as a proper noun. I'll propose adding a rule to our MD lint config to standardize.

2022-11-08 09:40 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +* Deploying using Shipyard now uses specific image overrides determined by the `PRELOAD_IMAGES` variable.
Same comment about this being a test/dev feature, not a user feature.

2022-11-08 09:40 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +* Added a centralized script for getting `subctl`. It now impersonates `subctl` so that users who run `make shell` will have it
Same comment about this being a test/dev feature, not a user feature.

2022-11-08 09:40 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +* All `shflags` usage has been removed from Shipyard and consuming projects.
Same comment about this being a test/dev feature, not a user feature.

2022-11-08 09:40 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +be used to verify if `submariner_router` is pinned to the proper Gateway node.
This looks like a fragment, not a full line?

2022-11-08 09:40 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +* If it’s not given a custom directory, `subctl gather` stores all its output in a directory
Can we put this gather dir change with the others? At least adjacent, maybe as one point or sublist?

2022-11-08 10:17 UTC, dfarrell07 requested changes

2022-11-08 10:17 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +* Privileges of the Route Agent and Gateway pods were reduced as they don’t need to access persistentvolumeclaims and secrets.
```suggestion
* Privileges of the Route Agent and Gateway pods were reduced as they don’t need to access PersistentVolumeClaims and Secrets.
```

https://kubernetes.io/docs/contribute/style/style-guide/#referring-to-kubernetes-api-resources
https://kubernetes.io/docs/concepts/storage/persistent-volumes/

I still find the code style guidance confusing, but for sure they should be UpperCamel.

2022-11-08 10:17 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +* Cloud cleanup for OpenStack now identifies and deletes failed machinesets.
```suggestion
* Cloud cleanup for OpenStack now identifies and deletes failed MachineSets.
```

2022-11-08 10:17 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +* The `subctl gather` command now includes the output from `ovn-sbctl show` which has the chassis-id to hostname mapping that can
```suggestion
* The `subctl gather` command now includes the output from `ovn-sbctl show` which has the `chassis-id` to `hostname` mapping that can
```
If these are field names, they should be `code case`.

https://kubernetes.io/docs/contribute/style/style-guide/#use-code-style-for-object-field-names-and-namespaces

2022-11-09 14:05 UTC, dfarrell07 commented on src/content/community/releases/_index.en.md
> +Be used to verify if `submariner_router` is pinned to the proper Gateway node.
```suggestion
Be used to verify if `submariner_router` is pinned to the proper Gateway node.
```
We still have this fragment, not clearly related to either of the adjacent points.

2022-11-10 09:19 UTC, dfarrell07 approved these changes
LGTM, thanks!

2022-11-21 15:15 UTC, nyechiel approved these changes

2022-11-21 15:19 UTC, dfarrell07 commented
See discussion of the Netlify failures here: https://github.com/submariner-io/submariner-website/pull/851#issuecomment-1308364701

2022-11-23 14:25 UTC, merged