Release notes for 0.15.1
submariner-io/submariner-website pull request #945
Opened 2023-06-06 09:31 UTC by yboaron

2023-06-06 12:12 UTC, tpantelis requested changes

2023-06-06 12:12 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +* Fixed IPsec pluto crash when remote endpoint is unstable.
To be consistent with https://github.com/submariner-io/submariner-website/pull/944/files.

```suggestion
* Fixed issue which caused the IPsec pluto process to crash when the remote endpoint was unstable.
```

2023-06-06 12:12 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +* Avoid cableEngine cleanup when the gateway pod is deleted.
To be consistent with https://github.com/submariner-io/submariner-website/pull/944/files - I think you're referring to the same issue.

```suggestion
* Fixed issue where a Gateway pod restart caused data path disruption.
```

2023-06-06 12:12 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +
```suggestion
Service Discovery now publishes DNS records for pods that are not ready for headless services based on the setting of the `publishNotReadyAddresses` flag on the Service.
```

2023-06-06 12:47 UTC, yboaron commented on src/content/community/releases/_index.en.md
> +* Avoid cableEngine cleanup when the gateway pod is deleted.
I think it should be gateway deleted and not gateway restarted.

cc @sridhargaddam

2023-06-06 13:13 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +* Avoid cableEngine cleanup when the gateway pod is deleted.
They're essentially equivalent b/c a deletion causes a restart. But a restart can occur for other reasons so I think it's more accurate here.

2023-06-06 13:57 UTC, skitt approved these changes

2023-06-06 15:44 UTC, sridhargaddam approved these changes

2023-06-06 16:22 UTC, tpantelis requested changes

2023-06-06 16:22 UTC, tpantelis commented on src/content/community/releases/_index.en.md
> +* Fixed issue where a Gateway pod deletion caused data path disruption..
Duplicate period at the end. 

Not trying to nitpick but I still think "restarted" is more appropriate. We delete pods in testing to effect a restart but I don't think an end user would do that. From the PR https://github.com/submariner-io/submariner/pull/2499, the scenario was due to a gateway failover restart, not explicit deletion of a pod.

2023-06-07 08:40 UTC, yboaron commented on src/content/community/releases/_index.en.md
> +* Fixed issue where a Gateway pod deletion caused data path disruption..
> Duplicate period at the end.

Ooops, thanks.

 https://github.com/submariner-io/submariner/pull/2499 avoid DP cleanup when GW is terminated due to SIGINT or SIGERM signals. 

'Kubectl delete pod'  command triggers a SIGTERM signal to pod's main process ID.

So, ^^ PR should help when pod is deleted and also in some GW restart use cases. 

I'll update this item.

2023-06-07 11:37 UTC, tpantelis approved these changes

2023-06-07 17:44 UTC, merged