Document 'subctl cloud prepare azure' command `air-gapped` flag
submariner-io/submariner-website pull request #951
Opened 2023-06-13 17:36 UTC by tpantelis

2023-06-14 14:08 UTC, skitt requested changes
This targets the wrong branch, `release-notes_0.16` has been merged. I’ll fix the PR.

2023-06-14 14:08 UTC, skitt commented on src/content/community/releases/_index.en.md
> +* The `subctl cloud prepare azure` command now has a new flag, `air-gapped`, to indicate the cluster is in an air-gapped
```suggestion
* The `subctl cloud prepare azure` command has a new flag, `air-gapped`, to indicate the cluster is in an air-gapped
```

“now“ and “new” seem redundant here.

2023-06-14 14:39 UTC, skitt commented on .github/workflows/branch.yml
> +      - name: Check that the PR targets devel or a release note branch
Let’s do #954 instead.

2023-06-14 15:25 UTC, skitt approved these changes

2023-06-14 15:26 UTC, skitt approved these changes

2023-06-14 16:01 UTC, nyechiel approved these changes

2023-06-26 14:59 UTC, dfarrell07 commented
FYI, I can't merge these PRs into non-devel branches.

2023-06-26 15:15 UTC, merged