Add release notes for submariner#2532
submariner-io/submariner-website pull request #972
Opened 2023-07-05 11:45 UTC by sridhargaddam

Submariner now handles out-of-order remote endpoint notifications properly in Globalnet component.

Related to: https://github.com/submariner-io/submariner/pull/2536
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

2023-07-05 13:59 UTC, skitt requested changes

2023-07-05 13:59 UTC, skitt commented on src/content/community/releases/_index.en.md
> +* Submariner now handles out-of-order remote endpoint notifications properly in Globalnet component.
```suggestion
* The Globalnet component now handles out-of-order remote endpoint notifications properly.
```

2023-07-06 08:06 UTC, skitt approved these changes

2023-07-06 09:05 UTC, Jaanki approved these changes

2023-07-06 09:09 UTC, merged