Add release notes for submariner#2504
submariner-io/submariner-website pull request #974
Opened 2023-07-05 12:02 UTC by sridhargaddam

Submariner Gateway pod now skips invoking cableEngine cleanup during termination, as this is handled by the Route agent during gateway migration.

Related to: https://github.com/submariner-io/submariner/pull/2504
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

2023-07-05 13:59 UTC, skitt requested changes

2023-07-05 13:59 UTC, skitt commented on src/content/community/releases/_index.en.md
> +* Submariner Gateway pod now skips invoking cableEngine cleanup during termination, as this is handled by the Route agent
```suggestion
* Submariner gateway pods now skip cable engine cleanup during termination, as this is handled by the route agent
```

2023-07-06 08:06 UTC, skitt approved these changes

2023-07-06 09:04 UTC, Jaanki approved these changes

2023-07-06 09:08 UTC, merged