Add release notes for submariner#2537
submariner-io/submariner-website pull request #976
Opened 2023-07-05 12:21 UTC by sridhargaddam

Submariner now handles out-of-order remote endpoint notifications properly in Globalnet component.

Related to: https://github.com/submariner-io/submariner/pull/2537
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

2023-07-05 13:58 UTC, skitt requested changes

2023-07-05 13:58 UTC, skitt commented on src/content/community/releases/_index.en.md
> +* Submariner now handles out-of-order remote endpoint notifications properly in Globalnet component.
```suggestion
* The Globalnet component now handles out-of-order remote endpoint notifications properly.
```

2023-07-06 08:06 UTC, skitt approved these changes

2023-07-07 19:22 UTC, dfarrell07 approved these changes

2023-07-10 08:19 UTC, merged