Add release notes for submariner#2519
submariner-io/submariner-website pull request #978
Opened 2023-07-05 12:30 UTC by sridhargaddam

Submariner Gateway pod now skips invoking cableEngine cleanup during termination, as this is handled by the Route agent during gateway migration.

Related to: https://github.com/submariner-io/submariner/pull/2519
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

2023-07-05 13:57 UTC, skitt requested changes

2023-07-05 13:57 UTC, skitt commented on src/content/community/releases/_index.en.md
> +* Submariner Gateway pod now skips invoking cableEngine cleanup during termination, as this is handled by the Route agent
```suggestion
* Submariner gateway pods now skip cable engine cleanup during termination, as this is handled by the route agent
```

2023-07-06 08:05 UTC, skitt approved these changes

2023-07-10 08:37 UTC, maayanf24 approved these changes

2023-07-10 10:10 UTC, merged