Add release notes for couple of PRs
submariner-io/submariner-website pull request #979
Opened 2023-07-05 13:09 UTC by sridhargaddam

Includes the release notes for the following fixes.

* Submariner now uses case-insensitive comparison while parsing CNI names.
* subctl gather now collects Metrics proxy pod logs in a Globalnet deployment.
* Submariner Gateway pod now skips invoking cableEngine cleanup during termination, as this is handled by the Route agent during gateway migration.
* Fixed issue which caused the IPsec pluto process to crash when the remote endpoint was unstable.
* Submariner now handles out-of-order remote endpoint notifications properly in Globalnet component.

Related to: https://github.com/submariner-io/submariner/pull/2486
Related to: https://github.com/submariner-io/subctl/pull/770
Related to: https://github.com/submariner-io/submariner/pull/2499
Related to: https://github.com/submariner-io/submariner/pull/2517
Related to: https://github.com/submariner-io/submariner/pull/2532
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

2023-07-05 13:57 UTC, skitt requested changes

2023-07-05 13:57 UTC, skitt commented on src/content/community/releases/_index.en.md
> +* The `subctl gather` command now collects Metrics proxy pod logs in a Globalnet deployment.
```suggestion
* The `subctl gather` command now collects metrics proxy pod logs in Globalnet deployments.
```

2023-07-05 13:57 UTC, skitt commented on src/content/community/releases/_index.en.md
> +* Submariner Gateway pod now skips invoking cableEngine cleanup during termination, as this is handled by the Route agent
```suggestion
* Submariner gateway pods now skip cable engine cleanup during termination, as this is handled by the route agent
```

(not sure about the capitalisation...).

2023-07-05 13:57 UTC, skitt commented on src/content/community/releases/_index.en.md
> +* Submariner now handles out-of-order remote endpoint notifications properly in Globalnet component.
```suggestion
* The Globalnet component now handles out-of-order remote endpoint notifications properly.
```

2023-07-06 08:05 UTC, skitt approved these changes

2023-07-10 15:21 UTC, dfarrell07 approved these changes

2023-07-10 15:36 UTC, merged