Document the new release note process
submariner-io/submariner-website pull request #986
Opened 2023-07-06 12:26 UTC by skitt

2023-07-09 07:36 UTC, maayanf24 approved these changes

2023-07-10 14:35 UTC, dfarrell07 approved these changes
Looks great

2023-07-10 14:56 UTC, dfarrell07 commented
I sent https://github.com/submariner-io/submariner-website/pull/992 to fix one pre-existing issue with linktext.

2023-07-12 07:59 UTC, maayanf24 requested changes

2023-07-12 07:59 UTC, maayanf24 commented on src/content/development/contribution-guide/_index.en.md
> +[the website repository]: https://githu.com/submariner-io/submariner-website/
```suggestion
[the website repository]: https://github.com/submariner-io/submariner-website/
```

2023-07-12 08:17 UTC, maayanf24 approved these changes

2023-07-13 13:27 UTC, tpantelis approved these changes

2023-07-13 13:28 UTC, merged